name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          # Replace Firebase config placeholders in all HTML files
          for file in *.html; do
            sed -i "s/FIREBASE_API_KEY/$FIREBASE_API_KEY/g" "$file"
            sed -i "s/FIREBASE_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN/g" "$file"
            sed -i "s/FIREBASE_PROJECT_ID/$FIREBASE_PROJECT_ID/g" "$file"
            sed -i "s/FIREBASE_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET/g" "$file"
            sed -i "s/FIREBASE_MESSAGING_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID/g" "$file"
            sed -i "s/FIREBASE_APP_ID/$FIREBASE_APP_ID/g" "$file"
            sed -i "s/FIREBASE_MEASUREMENT_ID/$FIREBASE_MEASUREMENT_ID/g" "$file"
          done
          
          # Also replace placeholders in config.js
          sed -i "s/FIREBASE_API_KEY/$FIREBASE_API_KEY/g" config.js
          sed -i "s/FIREBASE_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN/g" config.js
          sed -i "s/FIREBASE_PROJECT_ID/$FIREBASE_PROJECT_ID/g" config.js
          sed -i "s/FIREBASE_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET/g" config.js
          sed -i "s/FIREBASE_MESSAGING_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID/g" config.js
          sed -i "s/FIREBASE_APP_ID/$FIREBASE_APP_ID/g" config.js
          sed -i "s/FIREBASE_MEASUREMENT_ID/$FIREBASE_MEASUREMENT_ID/g" config.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: . 